# Generated by Django 4.1.2 on 2022-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('metrica', models.CharField(max_length=100, verbose_name='Metrica')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor')),
            ],
        ),
    ]
